/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: F16ASCIIHNPMD.c                                       *
* Font:        HelveticaNeueLT Pro 65 Md                             *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007E                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontF16ASCIIHNPMD;

/* Start of unicode area <Control> */
GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0000[ 16] = { /* code 0000, <control> */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __X_____,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0022[ 16] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  ________,
  _XX_X___,
  _XXXX___,
  _XXXX___,
  _XX_X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0023[ 16] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  ___X_X__,
  __XX_X__,
  __X__X__,
  _XXXXXX_,
  __X__X__,
  __X__X__,
  XXXXXXX_,
  __X_X___,
  __X_X___,
  _XX_X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXX___,
  _X_X_X__,
  XX_X_XX_,
  XX_X____,
  _XXXXX__,
  __XXXXX_,
  ___X__XX,
  XX_X__XX,
  XX_X__XX,
  _XXXXX__,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0025[ 32] = { /* code 0025, PERCENT SIGN */
  ________,________,
  ________,________,
  ________,________,
  __XXX___,_X______,
  __X_X___,X_______,
  _XX_XX__,X_______,
  _XX_XX_X,________,
  __X_X__X,________,
  __XXX_X_,_XXX____,
  ______X_,XX_XX___,
  _____X__,XX_XX___,
  ____X___,_X_X____,
  ____X___,_XXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0026[ 32] = { /* code 0026, AMPERSAND */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXX__,________,
  __XXX___,________,
  _XX_XX_X,________,
  XX__XXXX,________,
  XX___XXX,________,
  XX___XXX,________,
  _XXXXX_X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0027[ 16] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ________,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  __X_____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_002A[ 16] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  __X_____,
  X_X_X___,
  _XXX____,
  _X_X____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _X___X__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _X___X__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  XX___XX_,
  XX___XX_,
  ____XX__,
  ___XXX__,
  __XXX___,
  _XX_____,
  XX______,
  XXXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  XX___XX_,
  _____X__,
  ___XX___,
  _____X__,
  _____XX_,
  XX___XX_,
  _X___XX_,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  ____XX__,
  ___XXX__,
  ___XXX__,
  __X_XX__,
  _XX_XX__,
  _X__XX__,
  XX__XX__,
  XXXXXXX_,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX_____,
  _X______,
  _X______,
  _XXXX___,
  XX___XX_,
  _____XX_,
  XX___XX_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX_XXX_,
  _X___XX_,
  XX______,
  XXXXX___,
  XX___X__,
  XX___XX_,
  XX___XX_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___XX___,
  ___X____,
  ___X____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__X__,
  __XXX___,
  _X___X__,
  XX___XX_,
  XX___XX_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXX___,
  _X__XX__,
  XX___X__,
  XX___XX_,
  XX___XX_,
  _X__XXX_,
  __XXXXX_,
  _____XX_,
  XXX_XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _______X,
  ____XXX_,
  __XXX___,
  _X______,
  __XXX___,
  ____XXX_,
  _______X,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_003D[ 16] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  ________,
  _XXXXXXX,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _XXX____,
  ___XXX__,
  ______XX,
  ___XXX__,
  _XXX____,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_003F[ 16] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  XX___XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0040[ 32] = { /* code 0040, COMMERCIAL AT */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __X_____,X_______,
  __X_XXX_,_X______,
  _X__X_XX,_X______,
  _X_X___X,_X______,
  _X_X__X_,_X______,
  _X_X__X_,X_______,
  _X__XXXX,________,
  __X_____,_X______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0041[ 32] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___X_X__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __X___XX,________,
  _XXXXXXX,________,
  _X_____X,________,
  XX_____X,X_______,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0042[ 32] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,________,
  _XXXXXX_,________,
  _XX____X,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0043[ 32] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  _XX___XX,________,
  _X_____X,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  _X_____X,X_______,
  _XX___XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0044[ 32] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XX____X,X_______,
  _XX_____,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,X_______,
  _XX____X,X_______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0045[ 32] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXXXX,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  _XXXXXXX,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXXX_,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0047[ 32] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  _XX____X,X_______,
  _XX_____,XX______,
  XX______,________,
  XX______,________,
  XX___XXX,XX______,
  XX______,XX______,
  _X______,XX______,
  _XX____X,XX______,
  ___XXXX_,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0048[ 32] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXXXXXX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_004B[ 32] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  _XX____X,X_______,
  _XX___XX,________,
  _XX__XX_,________,
  _XX_XX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XX__XX_,________,
  _XX___XX,________,
  _XX___XX,X_______,
  _XX____X,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXXXX,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_004D[ 32] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XX_X__X,_XX_____,
  _XX_X__X,_XX_____,
  _XX_X__X,_XX_____,
  _XX_XX_X,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_004E[ 32] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  _XX____X,X_______,
  _XXX___X,X_______,
  _XXX___X,X_______,
  _XXXX__X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX__XXX,X_______,
  _XX___XX,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_004F[ 32] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  _XX____X,X_______,
  _X______,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _X______,X_______,
  _XX____X,X_______,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0050[ 32] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXXXXXX,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0051[ 32] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  _XX____X,X_______,
  _X______,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _X___XXX,X_______,
  _XX___XX,X_______,
  ___XXXXX,XX______,
  ________,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0052[ 32] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,________,
  _XXXXXX_,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0053[ 32] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX_____,________,
  __XXXX__,________,
  ___XXXXX,________,
  ______XX,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0055[ 32] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0056[ 32] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  XX_____X,________,
  XX____XX,________,
  _X____XX,________,
  _XX___X_,________,
  _XX__XX_,________,
  __X__XX_,________,
  __XX_X__,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0057[ 32] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  XX___XX_,___XX___,
  XX___XXX,___X____,
  _X___XXX,___X____,
  _XX__X_X,__XX____,
  _XX_XX_X,__XX____,
  _XX_XX_X,X_X_____,
  __X_X__X,X_X_____,
  __X_X___,XXX_____,
  __XXX___,XX______,
  ___XX___,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0058[ 32] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X_______,
  _XX___XX,________,
  __XX_XX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX___XX,________,
  XX_____X,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0059[ 32] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,________,
  ________,________,
  ________,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XX_,________,
  __X__X__,________,
  __XXXX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_005A[ 32] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XXX____,________,
  _XX_____,________,
  XXXXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_005B[ 16] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ________,
  ________,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  ________,
  X_______,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  __X_____,
  __XX____,
  ___X____,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_005D[ 16] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  __XXXX__,
  __X__X__,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_005F[ 16] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  _____XX_,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  _XXXXXXX,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0062[ 32] = { /* code 0062, LATIN SMALL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXX__,________,
  _XX___X_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___X_,________,
  _XXXXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  XX___X__,
  XX______,
  XX___XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0064[ 32] = { /* code 0064, LATIN SMALL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  __XXX_XX,________,
  _XX__XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XXX,________,
  __XXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  XX___XX_,
  XXXXXXX_,
  XX______,
  _X___XX_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  __XX____,
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX_XX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXXXXX,
  ______XX,
  XXX___X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX__XXX,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  _XX__XX_,
  _XX___XX,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_006D[ 32] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXX_X,XX______,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0070[ 32] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXX__,________,
  _XX___X_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___X_,________,
  _XXXXX__,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0071[ 32] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXX_XX,________,
  _XX__XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  _XX__XXX,________,
  __XXXXXX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX__XXX_,
  XXX_____,
  _XXXXX__,
  _____XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X___X__,
  _XX__X__,
  _XX_XX__,
  __X_X___,
  __XXX___,
  ___XX___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0077[ 32] = { /* code 0077, LATIN SMALL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__XX__,_X______,
  _X__XX__,XX______,
  _X__X_X_,XX______,
  _XX_X_X_,X_______,
  __XXX_X_,X_______,
  __XX__XX,X_______,
  __XX___X,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _XX_XX__,
  __XXX___,
  ___XX___,
  __XXX___,
  _XX_XX__,
  XX___XX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X___XX_,
  _XX__X__,
  _XX_XX__,
  __X_X___,
  __XXX___,
  __XXX___,
  ___X____,
  __XX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ____XX__,
  ___XX___,
  __XX____,
  __X_____,
  _XX_____,
  XXXXXXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ________,
  ________,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  X_______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_007C[ 16] = { /* code 007C, VERTICAL LINE */
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ___X____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontF16ASCIIHNPMD_007E[ 16] = { /* code 007E, TILDE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX__X_,
  _X__XXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontF16ASCIIHNPMD_CharInfo[96] = {
   {   7,   7,  1, acGUI_FontF16ASCIIHNPMD_0000 } /* code 0000 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0020 } /* code 0020 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0021 } /* code 0021 */
  ,{   6,   6,  1, acGUI_FontF16ASCIIHNPMD_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0024 } /* code 0024 */
  ,{  14,  14,  2, acGUI_FontF16ASCIIHNPMD_0025 } /* code 0025 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0026 } /* code 0026 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0027 } /* code 0027 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0028 } /* code 0028 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0029 } /* code 0029 */
  ,{   5,   5,  1, acGUI_FontF16ASCIIHNPMD_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_002B } /* code 002B */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_002C } /* code 002C */
  ,{   5,   5,  1, acGUI_FontF16ASCIIHNPMD_002D } /* code 002D */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_002E } /* code 002E */
  ,{   5,   5,  1, acGUI_FontF16ASCIIHNPMD_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0039 } /* code 0039 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_003A } /* code 003A */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_003F } /* code 003F */
  ,{  11,  11,  2, acGUI_FontF16ASCIIHNPMD_0040 } /* code 0040 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0041 } /* code 0041 */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_0042 } /* code 0042 */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_0043 } /* code 0043 */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_0044 } /* code 0044 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0046 } /* code 0046 */
  ,{  11,  11,  2, acGUI_FontF16ASCIIHNPMD_0047 } /* code 0047 */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_0048 } /* code 0048 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_004A } /* code 004A */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_004C } /* code 004C */
  ,{  12,  12,  2, acGUI_FontF16ASCIIHNPMD_004D } /* code 004D */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_004E } /* code 004E */
  ,{  11,  11,  2, acGUI_FontF16ASCIIHNPMD_004F } /* code 004F */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0050 } /* code 0050 */
  ,{  11,  11,  2, acGUI_FontF16ASCIIHNPMD_0051 } /* code 0051 */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_0052 } /* code 0052 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0054 } /* code 0054 */
  ,{  10,  10,  2, acGUI_FontF16ASCIIHNPMD_0055 } /* code 0055 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0056 } /* code 0056 */
  ,{  13,  13,  2, acGUI_FontF16ASCIIHNPMD_0057 } /* code 0057 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0058 } /* code 0058 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0059 } /* code 0059 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_005A } /* code 005A */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_005B } /* code 005B */
  ,{   5,   5,  1, acGUI_FontF16ASCIIHNPMD_005C } /* code 005C */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_005E } /* code 005E */
  ,{   7,   7,  1, acGUI_FontF16ASCIIHNPMD_005F } /* code 005F */
  ,{   3,   3,  1, acGUI_FontF16ASCIIHNPMD_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0061 } /* code 0061 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0063 } /* code 0063 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0065 } /* code 0065 */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0068 } /* code 0068 */
  ,{   3,   3,  1, acGUI_FontF16ASCIIHNPMD_0069 } /* code 0069 */
  ,{   3,   3,  1, acGUI_FontF16ASCIIHNPMD_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_006B } /* code 006B */
  ,{   3,   3,  1, acGUI_FontF16ASCIIHNPMD_006C } /* code 006C */
  ,{  12,  12,  2, acGUI_FontF16ASCIIHNPMD_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_006F } /* code 006F */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0070 } /* code 0070 */
  ,{   9,   9,  2, acGUI_FontF16ASCIIHNPMD_0071 } /* code 0071 */
  ,{   5,   5,  1, acGUI_FontF16ASCIIHNPMD_0072 } /* code 0072 */
  ,{   7,   7,  1, acGUI_FontF16ASCIIHNPMD_0073 } /* code 0073 */
  ,{   5,   5,  1, acGUI_FontF16ASCIIHNPMD_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0075 } /* code 0075 */
  ,{   7,   7,  1, acGUI_FontF16ASCIIHNPMD_0076 } /* code 0076 */
  ,{  11,  11,  2, acGUI_FontF16ASCIIHNPMD_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_0078 } /* code 0078 */
  ,{   7,   7,  1, acGUI_FontF16ASCIIHNPMD_0079 } /* code 0079 */
  ,{   7,   7,  1, acGUI_FontF16ASCIIHNPMD_007A } /* code 007A */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_007B } /* code 007B */
  ,{   3,   3,  1, acGUI_FontF16ASCIIHNPMD_007C } /* code 007C */
  ,{   4,   4,  1, acGUI_FontF16ASCIIHNPMD_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_FontF16ASCIIHNPMD_007E } /* code 007E */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontF16ASCIIHNPMD_Prop2 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontF16ASCIIHNPMD_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontF16ASCIIHNPMD_Prop1 = {
   0x0000 /* first character */
  ,0x0000 /* last character  */
  ,&GUI_FontF16ASCIIHNPMD_CharInfo[  0] /* address of first character */
  ,&GUI_FontF16ASCIIHNPMD_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontF16ASCIIHNPMD = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontF16ASCIIHNPMD_Prop1}
  ,13 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

