#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

[ "$ACTION" = "start" ] && {
#	config_load network
	config_load iptv
	
#	config_get _igmp "lan" igmp_snooping
	config_get _iptv "iptv" enable
#	[ "$_igmp" = "1" -a "$_iptv" = "on" ] && {
	[ "$_iptv" = "on" ] && {
		# Add filter rules
		local r1 r2 r3
	
		r1=$(fw list 4 f zone_wan|grep "\-p igmp")
		[ -z "$r1" ] && fw add 4 f zone_wan ACCEPT ^ { -p igmp }
		
		r2=$(fw list 4 f zone_wan|grep "\-d 224.0.0.0/4")
		[ -z "$r2" ] && fw add 4 f zone_wan ACCEPT ^ { -p udp -d 224.0.0.0/4 }
		
		r3=$(fw list 4 f zone_wan_forward|grep "\-d 224.0.0.0/4")
		[ -z "$r3" ] && fw add 4 f zone_wan_forward zone_lan_ACCEPT ^ { -p udp -d 224.0.0.0/4 }
	}
}
