#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=46

AC_LIBDIR=/lib/basic_security

ac() {
	. $AC_LIBDIR/core.sh
	fw_$1
}

start() {
	ac start
}

stop() {
	ac stop
}

restart() {
	ac restart
}

reload() {
	ac reload
}
