#!/bin/sh /etc/rc.common
# Copyright (c) 2014 The Linux Foundation. All rights reserved.
# Copyright (C) 2010-2014 OpenWrt.org

START=99
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
CONF_FILE="/etc/improxy.conf"

improxy_pinstance() {
	local upstream downstream

	#default WAN
	config_load network
	config_get upstream wan ifname
	echo -e "upstream \t$upstream" >>$CONF_FILE
	
	#default LAN
	config_load network
	config_get downstream lan ifname
	echo -e "downstream \t$downstream" >>$CONF_FILE
}

igmp_add_fw_rules() {
	local r1 r2 r3
	
	r1=$(fw list 4 f zone_wan|grep "\-p igmp")
	[ -z "$r1" ] && fw add 4 f zone_wan ACCEPT ^ { -p igmp }
	
	r2=$(fw list 4 f zone_wan|grep "\-d 224.0.0.0/4")
	[ -z "$r2" ] && fw add 4 f zone_wan ACCEPT ^ { -p udp -d 224.0.0.0/4 }
	
	r3=$(fw list 4 f zone_wan_forward|grep "\-d 224.0.0.0/4")
	[ -z "$r3" ] && fw add 4 f zone_wan_forward zone_lan_ACCEPT ^ { -p udp -d 224.0.0.0/4 }
}

igmp_del_fw_rules() {
	fw del 4 f zone_wan ACCEPT { -p igmp }
	fw del 4 f zone_wan ACCEPT { -p udp -d 224.0.0.0/4 }
	fw del 4 f zone_wan_forward zone_lan_ACCEPT { -p udp -d 224.0.0.0/4 }
}

start() {
#	local status
#	config_load network
	local igmp_enable 
	local igmp_version
	config_load iptv
	
#	config_get status "lan" igmp_snooping
	config_get igmp_enable "iptv" igmp_enable 
#	if [ "$status" = "1" -a "$iptv_on" = "on" ]; then
	if [ "$igmp_enable" = "on" ]; then
		config_get igmp_version "iptv" igmp_version "2"
		echo $igmp_version > /proc/sys/net/ipv4/conf/all/force_igmp_version
		echo 60 > /proc/sys/net/ipv4/igmp_max_memberships
		
		igmp_add_fw_rules			
		echo -e "igmp \tenable \tversion \t$igmp_version" >$CONF_FILE
		echo -e "mld \tenable" >>$CONF_FILE
		
		improxy_pinstance
		
		service_start /usr/sbin/improxy -c $CONF_FILE -p "/tmp/improxy.pid"
	else
		igmp_del_fw_rules
		echo 2 > /proc/sys/net/ipv4/conf/all/force_igmp_version
	fi
	
	return 0
}

stop() {	
	service_stop /usr/sbin/improxy
	return 0
}
