#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for system monitor.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 3 Jul, 2014

START=50

SERVICE_DAEMONIZE=1

start() {
    service_start /usr/sbin/sysmond
}

stop() {
    service_stop /usr/sbin/sysmond
}
