#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for tsched.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 27 Mar, 2014

START=50

SERVICE_DAEMONIZE=1 

start() {
    service_start /usr/sbin/tsched
}

stop() {
    cat 1>&2 <<EOF
You shouldn't stop it. It will cause troubles so far.
If you know what you are doing, please manually kill it.
EOF
    return 1
}

reload() {
    # TODO: create update file for each module.
    return 1
}

restart() {
    stop "$@" && start "$@"
}
