#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

[ "$INTERFACE" == "lan" ] && exit 0

local iface
local wan_type

config_load network
config_get wan_type "wan" wan_type
 
case $wan_type in
    static|dhcp) iface="wan" ;;
    *) iface="internet" ;;
esac

[ "$iface" != "$INTERFACE" ] && return 0

CLOUD_CLIENT_OBJECT="cloudclient"

local ubus_object=$(ubus list | grep cloudclient)
[ $ubus_object == $CLOUD_CLIENT_OBJECT ] || exit 0

case "$ACTION" in
    ifup)
        ubus call cloudclient construct_ssl_path '{"service_type":1}'
    ;;
    ifdown)
        ubus call cloudclient construct_ssl_path '{"service_type":2}'
    ;;
esac

