/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: QS_BarFutureBmp                                       *
* Dimensions:  8 * 8                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmQS_BarFutureBmp;

static GUI_CONST_STORAGE unsigned long _acQS_BarFutureBmp[] = {
  0xFFC2BFB3, 0xDAC2BFB3, 0x52C2BFB3, 0x0EC2BFB3, 0x0EC2BFB3, 0x52C2BFB3, 0xDAC2BFB3, 0xFFC2BFB3,
  0xD8C2BFB3, 0x10C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x10C2BFB3, 0xD8C2BFB3,
  0x52C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x52C2BFB3,
  0x0EC2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x0CC2BFB3,
  0x0EC2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x0CC2BFB3,
  0x52C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x52C2BFB3,
  0xD7C2BFB3, 0x10C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x00C2BFB3, 0x10C2BFB3, 0xD7C2BFB3,
  0xFFC2BFB3, 0xD8C2BFB3, 0x52C2BFB3, 0x0DC2BFB3, 0x0DC2BFB3, 0x52C2BFB3, 0xD8C2BFB3, 0xFFC2BFB3
};

GUI_CONST_STORAGE GUI_BITMAP bmQS_BarFutureBmp = {
  8, // xSize
  8, // ySize
  32, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acQS_BarFutureBmp,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
