/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: QS_BarNowBmp                                          *
* Dimensions:  14 * 14                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmQS_BarNowBmp;

static GUI_CONST_STORAGE unsigned long _acQS_BarNowBmp[] = {
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xEB4DCB88, 0x794DCB88, 0x2D4DCB88, 0x074DCB88, 0x074DCB88, 0x2F4DCB88, 0x7D4DCB88, 0xEB4DCB88, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFF4DCB88, 0xAC4DCB88, 0x0F51CC8A, 0x0092D8AD, 0x00C9E2CB, 0x00E5E8DA, 0x00E5E8DA, 0x00C9E2CB, 0x0090D8AC, 0x0E51CC8A, 0xAC4DCB88, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0xAC4DCB88, 0x015DCE91, 0x00CDE3CD, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00CEE3CE, 0x015DCE91, 0xAC4DCB88, 0xFFFFFFFF,
  0xEA4DCB88, 0x0E51CC8A, 0x00CEE3CE, 0x00ECE9DE, 0x00D5E5D2, 0x0080D5A4, 0x0056CD8D, 0x0056CD8D, 0x0080D5A4, 0x00D5E5D2, 0x00ECE9DE, 0x00CFE3CE, 0x0E51CC8A, 0xE94DCB88,
  0x7D4DCB88, 0x0093D8AE, 0x00ECE9DE, 0x00D4E4D1, 0x0057CD8D, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0057CD8D, 0x00D4E4D1, 0x00ECE9DE, 0x0093D8AE, 0x794DCB88,
  0x2F4DCB88, 0x00C9E2CB, 0x00ECE9DE, 0x0080D5A4, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0080D5A4, 0x00ECE9DE, 0x00C9E2CB, 0x2D4DCB88,
  0x074DCB88, 0x00E8E8DC, 0x00ECE9DE, 0x0056CD8D, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0054CC8C, 0x00ECE9DE, 0x00E8E8DC, 0x064DCB88,
  0x074DCB88, 0x00E8E8DC, 0x00ECE9DE, 0x0056CD8D, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0054CC8C, 0x00ECE9DE, 0x00E5E8DA, 0x0C4DCB88,
  0x2F4DCB88, 0x00C9E2CB, 0x00ECE9DE, 0x0080D5A4, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0080D5A4, 0x00ECE9DE, 0x00C9E2CB, 0x2E4DCB88,
  0x7D4DCB88, 0x0091D8AD, 0x00ECE9DE, 0x00D3E4D1, 0x0057CD8D, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0057CD8D, 0x00D3E4D1, 0x00ECE9DE, 0x0090D8AC, 0x794DCB88,
  0xE94DCB88, 0x0E51CC8A, 0x00CFE3CE, 0x00ECE9DE, 0x00D4E4D1, 0x0080D5A4, 0x0055CD8C, 0x0055CD8C, 0x0080D5A4, 0x00D4E4D1, 0x00ECE9DE, 0x00CFE4CE, 0x0E51CC8A, 0xE94DCB88,
  0xFFFFFFFF, 0xAC4DCB88, 0x015ECE91, 0x00CEE3CE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00ECE9DE, 0x00CEE3CE, 0x015ECE91, 0xAC4DCB88, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xAB4DCB88, 0x0D51CC8A, 0x0092D8AD, 0x00C9E2CB, 0x00E5E8DA, 0x00E5E8DA, 0x00C9E2CB, 0x0090D8AC, 0x0D51CC8A, 0xAC4DCB88, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xEB4DCB88, 0x794DCB88, 0x2C4DCB88, 0x054DCB88, 0x0B4DCB88, 0x314DCB88, 0x7C4DCB88, 0xEB4DCB88, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP bmQS_BarNowBmp = {
  14, // xSize
  14, // ySize
  56, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acQS_BarNowBmp,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
