/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: QS_BarPassedBmp                                       *
* Dimensions:  8 * 8                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmQS_BarPassedBmp;

static GUI_CONST_STORAGE unsigned long _acQS_BarPassedBmp[] = {
  0xFF4DCB88, 0xDA4DCB88, 0x524DCB88, 0x0E4DCB88, 0x0E4DCB88, 0x524DCB88, 0xDA4DCB88, 0xFF4DCB88,
  0xD84DCB88, 0x104DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x104DCB88, 0xD84DCB88,
  0x524DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x524DCB88,
  0x0E4DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0C4DCB88,
  0x0E4DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x0C4DCB88,
  0x524DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x524DCB88,
  0xD74DCB88, 0x104DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x004DCB88, 0x104DCB88, 0xD74DCB88,
  0xFF4DCB88, 0xD84DCB88, 0x524DCB88, 0x0D4DCB88, 0x0D4DCB88, 0x524DCB88, 0xD84DCB88, 0xFF4DCB88
};

GUI_CONST_STORAGE GUI_BITMAP bmQS_BarPassedBmp = {
  8, // xSize
  8, // ySize
  32, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acQS_BarPassedBmp,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
