/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FAKELIST_RightArrowBmp                                *
* Dimensions:  7 * 12                                                *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmFAKELIST_RightArrowBmp;

static GUI_CONST_STORAGE unsigned long _acFAKELIST_RightArrowBmp[] = {
  0x2DB5B5B5, 0x4FB5B5B5, 0xF7B5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5,
  0x56B5B5B5, 0x00B5B5B5, 0x45B5B5B5, 0xF5B5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5,
  0xFAB5B5B5, 0x54B5B5B5, 0x00B5B5B5, 0x41B5B5B5, 0xF4B5B5B5, 0xFFB5B5B5, 0xFFB5B5B5,
  0xFFB5B5B5, 0xFCB5B5B5, 0x59B5B5B5, 0x00B5B5B5, 0x3DB5B5B5, 0xF2B5B5B5, 0xFFB5B5B5,
  0xFFB5B5B5, 0xFFB5B5B5, 0xFCB5B5B5, 0x5EB5B5B5, 0x00B5B5B5, 0x3BB5B5B5, 0xF0B5B5B5,
  0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFCB5B5B5, 0x63B5B5B5, 0x00B5B5B5, 0x3CB5B5B5,
  0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFDB5B5B5, 0x64B5B5B5, 0x00B5B5B5, 0x3BB5B5B5,
  0xFFB5B5B5, 0xFFB5B5B5, 0xFCB5B5B5, 0x5FB5B5B5, 0x00B5B5B5, 0x39B5B5B5, 0xF0B5B5B5,
  0xFFB5B5B5, 0xFCB5B5B5, 0x5AB5B5B5, 0x00B5B5B5, 0x3CB5B5B5, 0xF1B5B5B5, 0xFFB5B5B5,
  0xFAB5B5B5, 0x56B5B5B5, 0x00B5B5B5, 0x3FB5B5B5, 0xF4B5B5B5, 0xFFB5B5B5, 0xFFB5B5B5,
  0x57B5B5B5, 0x00B5B5B5, 0x44B5B5B5, 0xF5B5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5,
  0x2CB5B5B5, 0x4FB5B5B5, 0xF6B5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5, 0xFFB5B5B5
};

GUI_CONST_STORAGE GUI_BITMAP bmFAKELIST_RightArrowBmp = {
  7, // xSize
  12, // ySize
  28, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acFAKELIST_RightArrowBmp,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
