#!/bin/sh

ifup_all=
setup_wifi=

if_call() {
	local interface="$1"
	for mode in $modes; do
        # up or down lan independently
        if [ -n "$ifup_all" -a  "$interface" != "lan" ]; then
            ubus call network.interface $mode "{ \"interface\" : \"$interface\" }"
        fi
	done
}

case "$0" in
	*ifdown) modes=down;;
	*ifup)
		modes="down up"
		setup_wifi=
	;;
	*) echo "Invalid command: $0";;
esac

while :; do
	case "$1" in
		-a)
			ifup_all=1
			shift
		;;
		-w)
			setup_wifi=
			shift
		;;
		*)
			break
		;;
	esac
done

[ "$modes" = "down up" ] && ubus call network reload
if [ -n "$ifup_all" ]; then
	ifaces=`ubus -S list 'network.interface.*'`
	echo $ifaces | grep internet 1>/dev/null 2>&1 && {
		ubus call network.interface.internet disconnect 1>/dev/null 2>&1
		sleep 2
	}
	echo $ifaces | grep wanv6 1>/dev/null 2>&1 && {
               ubus call network.interface.wanv6 disconnect 1>/dev/null 2>&1
               sleep 2
       }

	for interface in $ifaces; do
		if_call "${interface##network.interface.}"
	done
	[ -n "$setup_wifi" ] && /sbin/wifi up
	exit
else
	ubus -S list "network.interface.$1" > /dev/null || {
		echo "Interface $1 not found"
		exit
	}
	if_call "$1"
fi

if [ -n "$setup_wifi" ] && grep -sq config /etc/config/wireless; then
	. /lib/functions.sh

	find_related_radios() {
		local wdev wnet
		config_get wdev "$1" device
		config_get wnet "$1" network

		if [ -n "$wdev" ]; then
			for wnet in $wnet; do
				if [ "$wnet" = "$network" ]; then
					append radio_devs "$wdev" "$N"
				fi
			done
		fi
	}

	local radio_devs
	local network="$1"
	config_load wireless
	config_foreach find_related_radios wifi-iface

	local dev
	for dev in $(echo "$radio_devs" | sort -u); do
		/sbin/wifi up "$dev"
	done
fi
