language: c
compiler:
 - clang
 - gcc
before_install: sudo apt-get update
install: sudo apt-get install bc valgrind perl
script:
 - cmake -D CMAKE_BUILD_TYPE:String="Check" .
 - make
 - make test
 - ( cd tests && ./compat.sh )
