/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.24.            *
*        Compiled Jan 27 2014, 08:56:32                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DP_TickBmp                                            *
* Dimensions:  16 * 11                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmDP_TickBmp;

static GUI_CONST_STORAGE unsigned long _acDP_TickBmp[] = {
  0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCE4DCB88, 0x1D4DCB88, 0x4F4DCB88,
  0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCE4DCB88, 0x134DCB88, 0x004DCB88, 0x1E4DCB88,
  0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCD4DCB88, 0x124DCB88, 0x004DCB88, 0x144DCB88, 0xCF4DCB88,
  0xF24DCB88, 0xE34DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCD4DCB88, 0x114DCB88, 0x004DCB88, 0x154DCB88, 0xD04DCB88, 0xFF4DCB88,
  0x254DCB88, 0x054DCB88, 0xA94DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCC4DCB88, 0x114DCB88, 0x004DCB88, 0x154DCB88, 0xD04DCB88, 0xFF4DCB88, 0xFF4DCB88,
  0x374DCB88, 0x004DCB88, 0x034DCB88, 0xA84DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCB4DCB88, 0x104DCB88, 0x004DCB88, 0x154DCB88, 0xD24DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88,
  0xEA4DCB88, 0x2F4DCB88, 0x004DCB88, 0x034DCB88, 0xA64DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xCB4DCB88, 0x104DCB88, 0x004DCB88, 0x154DCB88, 0xD34DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88,
  0xFF4DCB88, 0xEB4DCB88, 0x304DCB88, 0x004DCB88, 0x034DCB88, 0xA54DCB88, 0xC94DCB88, 0x0F4DCB88, 0x004DCB88, 0x164DCB88, 0xD44DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88,
  0xFF4DCB88, 0xFF4DCB88, 0xEB4DCB88, 0x304DCB88, 0x004DCB88, 0x034DCB88, 0x0D4DCB88, 0x004DCB88, 0x164DCB88, 0xD54DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88,
  0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xEC4DCB88, 0x314DCB88, 0x004DCB88, 0x004DCB88, 0x174DCB88, 0xD54DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88,
  0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xEC4DCB88, 0x3B4DCB88, 0x214DCB88, 0xD64DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88, 0xFF4DCB88
};

GUI_CONST_STORAGE GUI_BITMAP bmDP_TickBmp = {
  16, // xSize
  11, // ySize
  64, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acDP_TickBmp,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
